services:
  - type: web
    name: git_api_modular
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
